name: My first workflow

on:  
  workflow_dispatch:

jobs:
  Tarea1:
    runs-on: ubuntu-latest

    steps:
      - name: Digo Hola
        run: echo "Hola a todos"

      - name: Quien soy
        run: whoami

      - name: Fecha de hoy
        run: date
